FROM golang:1.6

RUN go get github.com/mholt/caddy

COPY caddy /caddy

RUN mkdir -p /home/caddy/logs
RUN mkdir -p /home/caddy/.caddy
ENV HOME /home/caddy
WORKDIR /home/caddy

ENTRYPOINT ["caddy", "-conf", "/caddy/Caddyfile", "-root", "/caddy/public", "-quiet"]

EXPOSE 80
